config/routes.rb
Rails.application.routes.draw do
  get 'google_images_scraper/index'
  get 'marvel_images_scraper/index'
  get 'marvel_films_scraper/index'
  get 'home_page/index'

  root 'home_page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/google_images_scraper_controller.rb
class GoogleImagesScraperController < ApplicationController
  def index
    @marvel_scraper = MarvelFilmsScraper.scrape
    @google_images = GoogleImagesScraper.scrape(@marvel_scraper.map(&:first))
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/marvel_films_scraper_controller.rb
class MarvelFilmsScraperController < ApplicationController
  def index
    @marvel_scraper = MarvelFilmsScraper.scrape
  end
end

app/controllers/marvel_images_scraper_controller.rb
class MarvelImagesScraperController < ApplicationController
  def index
    @marvel_scraper = MarvelFilmsScraper.scrape
    @google_images = MarvelImagesScraper.scrape
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/google_images_scraper_helper.rb
module GoogleImagesScraperHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/marvel_films_scraper_helper.rb
module MarvelFilmsScraperHelper
end

app/helpers/marvel_images_scraper_helper.rb
module MarvelImagesScraperHelper
end

app/views/google_images_scraper/index.html.erb
<h1>Images from Google</h1>
<p>Images scraped from images.google.com</p>
<p><%= link_to "Home", home_page_index_path %></p>
<p><%= link_to "Scrape films  from Marvel", marvel_films_scraper_index_path %></p>
<p><%= link_to "Scrape images from Marvel", marvel_images_scraper_index_path %></p>
<p>
</p>
<table>
  <tr>
    <th>Film</th>
    <th>Date</th>
    <th>image</th>
  </tr>

  <% @marvel_scraper.each_with_index do |film, i| %>
    <tr>
      <td><%= film[0] %></td>
      <td><%= film[1] %></td>
      <td><img src="<%=@google_images[i]%>" alt="<%=film[0]%>"></td>
    </tr>
  <% end %>
</table>

app/views/home_page/google_image_scrape.html.erb
<h1>Images from Google</h1>
<p>Images scraped from images.google.com</p>
<p><%= link_to "Home", home_page_path %></p>
<p><%= link_to "Scrape images from Marvel", marvel_image_scrape_path %></p>
<p>
</p>
<table>
  <tr>
    <th>Film</th>
    <th>Date</th>
    <th>image</th>
  </tr>

  <% @marvel_scraper.each_with_index do |film, i| %>
    <tr>
      <td><%= film[0] %></td>
      <td><%= film[1] %></td>
      <td><img src="<%=@google_images[i]%>" alt="<%=film[0]%>"></td>
    </tr>
  <% end %>
</table>

app/views/home_page/index.html.erb
<h1>Marvel Films</h1>
<p><%= link_to "Scrape films  from Marvel", marvel_films_scraper_index_path %></p>
<p><%= link_to "Scrape images from Google", google_images_scraper_index_path %></p>
<p><%= link_to "Scrape images from Marvel", marvel_images_scraper_index_path %></p>

app/views/home_page/marvel_image_scrape.html.erb
<h1>Images from Marvel</h1>
<p>Images scraped from https://www.marvel.com/movies</p>
<p><%= link_to "Home", home_page_path %></p>
<p><%= link_to "Scrape images from Google", google_image_scrape_path %></p>
<p>
</p>
<table>
  <tr>
    <th>Film</th>
    <th>Date</th>
    <th>image</th>
  </tr>

  <% @marvel_scraper.each_with_index do |film, i| %>
    <tr>
      <td><%= film[0] %></td>
      <td><%= film[1] %></td>
      <td><img src="<%=@google_images[i]%>" alt="<%=film[0]%>"></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scraper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marvel_films_scraper/index.html.erb
<h1>Marvel Films</h1>
<p>Scraped from https://www.marvel.com/movies</p>
<p><%= link_to "Home", home_page_index_path %></p>
<p><%= link_to "Scrape images from Google", google_images_scraper_index_path %></p>
<p><%= link_to "Scrape images from Marvel", marvel_images_scraper_index_path %></p>
<table>
  <tr>
    <th>Film</th>
    <th>Date</th>
  </tr>

  <% @marvel_scraper.each do |film| %>
    <tr>
      <td><%= film[0] %></td>
      <td><%= film[1] %></td>
    </tr>
  <% end %>
</table>

app/views/marvel_images_scraper/index.html.erb
<h1>Images from Marvel</h1>
<p>Images scraped from https://www.marvel.com/movies</p>
<p><%= link_to "Home", home_page_index_path %></p>
<p><%= link_to "Scrape films  from Marvel", marvel_films_scraper_index_path %></p>
<p><%= link_to "Scrape images from Google", google_images_scraper_index_path %></p>
<p>
</p>
<table>
  <tr>
    <th>Film</th>
    <th>Date</th>
    <th>image</th>
  </tr>

  <% @marvel_scraper.each_with_index do |film, i| %>
    <tr>
      <td><%= film[0] %></td>
      <td><%= film[1] %></td>
      <td><img src="<%=@google_images[i]%>" alt="<%=film[0]%>"></td>
    </tr>
  <% end %>
</table>